import { PrismaClient } from "@prisma/client";
import { type Game } from "../src/lib/constants";

const prisma = new PrismaClient();

const aircraftByGame: Record<Game, string[]> = {
  IL2_GB: [
    "Bf 109 F-4",
    "Bf 109 G-2",
    "Bf 109 G-4",
    "Bf 109 G-6",
    "Bf 109 G-14",
    "Bf 109 K-4",
    "Fw 190 A-3",
    "Fw 190 A-5",
    "Fw 190 A-8",
    "Fw 190 D-9",
    "Me 262 A",
    "Ju 87 D-3",
    "Ju 88 A-4",
    "He 111 H-6",
    "LaGG-3 ser.29",
    "Yak-1 ser.69",
    "Yak-7b ser.36",
    "Yak-1b ser.127",
    "La-5 ser.8",
    "La-5FN ser.2",
    "Il-2 mod.1941",
    "Il-2 mod.1942",
    "Il-2 mod.1943",
    "Pe-2 ser.87",
    "Pe-2 ser.35",
    "I-16 type 24",
    "MiG-3 ser.24",
    "P-40E-1",
    "P-39L-1",
    "P-47D-28",
    "P-51D-15",
    "P-38J-25",
    "Spitfire Mk.VB",
    "Spitfire Mk.IXe",
    "Spitfire Mk.XIV",
    "Tempest Mk.V ser.2",
    "Typhoon Mk.Ib",
    "Mosquito F.B. Mk.VI",
    "A-20B",
    "SPAD 13.C1",
    "Sopwith Camel",
    "Fokker Dr.I",
    "Fokker D.VII",
    "S.E.5a",
  ],
  IL2_KOREA: [
    "F-86F Sabre",
    "MiG-15bis",
    "F-80C Shooting Star",
    "Yak-9P",
    "La-9",
    "Il-10",
    "F-51D Mustang",
    "B-29 Superfortress",
  ],
  DCS: [
    "F/A-18C Hornet",
    "F-16C Viper",
    "A-10C Warthog",
    "A-10C II",
    "F-15C Eagle",
    "F-15E Strike Eagle",
    "F-14A Tomcat",
    "F-14B Tomcat",
    "F-4E Phantom II",
    "F-100D Super Sabre",
    "AJS-37 Viggen",
    "MiG-21bis",
    "MiG-19P",
    "MiG-29A",
    "Su-25",
    "Su-25T",
    "Su-27",
    "Su-33",
    "AH-64D Apache",
    "UH-1H Huey",
    "Mi-8MTV2",
    "Ka-50 Black Shark",
    "OH-58D",
    "P-47D Thunderbolt",
    "P-51D Mustang",
    "Spitfire LF Mk IX",
    "Bf 109 K-4",
    "Fw 190 D-9",
    "Mosquito FB VI",
    "F4U-1D Corsair",
    "C-101",
    "L-39",
    "Yak-52",
    "C-130J",
    "CH-47F Chinook",
  ],
  STAR_CITIZEN: [
    "Aurora MR",
    "Aurora LN",
    "Mustang Alpha",
    "Avenger Titan",
    "Cutter",
    "Gladius",
    "Arrow",
    "Sabre",
    "Sabre Raven",
    "Hurricane",
    "Hornet F7C",
    "Hornet F7C-S Ghost",
    "Eclipse",
    "Retaliator",
    "Hammerhead",
    "Polaris",
    "Idris-P",
    "Prospector",
    "MOLE",
    "Vulture",
    "Reclaimer",
    "Caterpillar",
    "Carrack",
    "400i",
    "600i",
    "Mercury Star Runner",
    "Constellation Andromeda",
    "Constellation Aquila",
    "Zeus Mk II ES",
    "Zeus Mk II MR",
    "Crusader C1 Spirit",
  ],
  MSFS: [
    "Cessna 172",
    "Cessna 208 Caravan",
    "Beechcraft Bonanza G36",
    "Piper PA-28",
    "Diamond DA40",
    "Boeing 747-8",
    "Boeing 787 Dreamliner",
    "Airbus A320neo",
    "Airbus A310",
    "Daher TBM 930",
    "Pilatus PC-6",
    "Eurofighter Typhoon (Top Gun Edition)",
    "F/A-18 (Top Gun Edition)",
    "Spitfire Mk. IX",
    "P-51D Mustang",
    "Junkers Ju 52",
    "Shock Ultra (ULM)",
    "Volocopter 2X",
    "Icon A5",
    "Pipistrel Virus SW",
  ],
};

async function main() {
  for (const game of Object.keys(aircraftByGame) as Game[]) {
    await prisma.aircraft.createMany({
      data: aircraftByGame[game].map((name) => ({
        name,
        game,
        isCustom: false,
      })),
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error: unknown) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
